## Домашнее задание 4

In [1]:
import pandas as pd
import numpy as np
import datetime

Вам дан файл `students_data.csv` с информацией о студентах и их оценками. 

* Задания с 1 по 5 весят по 0.5 баллов каждое
* Все остальные задания весят по 0.75

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/My Drive/Work/students_data.csv')
df.head()

index  gender race/ethnicity  ... math score reading score writing score
0    100    male        group B  ...         79            67            67
1    101    male        group D  ...         68            74            74
2    102  female        group D  ...         85            91            89
3    103    male        group B  ...         60            44            47
4    104    male        group C  ...         98            86            90

[5 rows x 10 columns]

## Задание 1

Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [4]:
df = df.drop(['index'],axis=1)
df.head(10)

gender race/ethnicity  ... reading score writing score
0    male        group B  ...            67            67
1    male        group D  ...            74            74
2  female        group D  ...            91            89
3    male        group B  ...            44            47
4    male        group C  ...            86            90
5  female        group C  ...            67            72
6  female        group D  ...           100           100
7    male        group E  ...            63            64
8  female        group B  ...            76            70
9  female        group B  ...            64            72

[10 rows x 9 columns]

## Задание 2

Выведите на экран размеры полученной таблицы. Сколько в ней строк и столбцов?

In [5]:
print(df.shape)

# В таблице 1000 строк и 9 столбцов

(1000, 9)


## Задание 3

Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [6]:
df.describe(include=[np.number]).loc[['min','max','mean','std']]

math score  reading score  writing score
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657

## Задание 4

Проверьте, есть ли в таблице пропущенные значения

In [9]:
df.isnull().values.any()

False

In [7]:
# ИЛИ вывести индексы строк с пропущенными значениями
df.isnull().any(1).index

# Пропущенных значений нет

RangeIndex(start=0, stop=1000, step=1)

## Задание 5

Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [195]:
print('Средний балл по математике:', df['math score'].mean())
print('Средний балл за чтение:', df['reading score'].mean())
print('Средний балл за письмо:', df['writing score'].mean())

Средний балл по математике: 66.089
Средний балл за чтение: 69.169
Средний балл за письмо: 68.054


## Задание 6

Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.

In [196]:
print('Средний балл по математике:') 
print('Прошедшие курс:', df.query("`test preparation course` == 'completed'")['math score'].mean(), 
      'Не прошедшие курс:', df.query("`test preparation course` == 'none'")['math score'].mean())
print('\n')
print('Средний балл за чтение:') 
print('Прошедшие курс:', df.query("`test preparation course` == 'completed'")['reading score'].mean(), 
      'Не прошедшие курс:', df.query("`test preparation course` == 'none'")['reading score'].mean())
print('\n')
print('Средний балл за письмо:') 
print('Прошедшие курс:', df.query("`test preparation course` == 'completed'")['writing score'].mean(), 
      'Не прошедшие курс:', df.query("`test preparation course` == 'none'")['writing score'].mean())

Средний балл по математике:
Прошедшие курс: 69.69553072625699 Не прошедшие курс: 64.0778816199377


Средний балл за чтение:
Прошедшие курс: 73.89385474860335 Не прошедшие курс: 66.53426791277259


Средний балл за письмо:
Прошедшие курс: 74.41899441340782 Не прошедшие курс: 64.50467289719626


In [197]:
# Проверка
df.pivot_table(index=['test preparation course'], values=['math score',	'reading score',	'writing score'], aggfunc='mean')

math score  reading score  writing score
test preparation course                                          
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

## Задание 7 

Выведите на экран все различные значения из столбца lunch.

In [198]:
np.unique(df['lunch'])

array(['free/reduced', 'standard'], dtype=object)

## Задание 8

Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas [rename](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html)

In [199]:
df = df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})

In [200]:
df.head()

gender race/ethnicity  ... reading score writing score
0    male        group B  ...            67            67
1    male        group D  ...            74            74
2  female        group D  ...            91            89
3    male        group B  ...            44            47
4    male        group C  ...            86            90

[5 rows x 9 columns]

**Зафиксируем минимальный балл для сдачи экзамена**

In [201]:
passmark = 50

## Задание 9

Ответьте на вопросы:
* Какая доля студентов сдала экзамен по математике (passmark >= 50)?
* Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
* Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике? 

In [202]:
(df['math score'] >= passmark).value_counts(normalize=True)*100

True     86.5
False    13.5
Name: math score, dtype: float64

```
86.5% студентов сдали экзамен по математике.
```



In [203]:
((df[df["test preparation"]=='completed'])['math score']>=50).value_counts(normalize=True)*100

True     92.178771
False     7.821229
Name: math score, dtype: float64



```
Из прошедших подготовительные курсы 92.18% сдали экзамен.
```



In [204]:
(df.loc[(df["gender"]=='female') & (df["test preparation"]=='none')]['math score']<50).value_counts(normalize=True)*100

False    79.041916
True     20.958084
Name: math score, dtype: float64



```
Из девушек, не проходивших подготовительные курсы, экзамен НЕ сдали 20.95% участниц.
```



## Задание 10

С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.
* Для каждой этнической группы выведите средний балл за экзамен по чтению
* Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [205]:
df.groupby(['race/ethnicity'])['reading score'].mean()

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

In [206]:
df.groupby(['education'])['writing score'].min()

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

## Задание 11

Выполните задание 10 с помощью циклов. Сравните время выполнения.

In [207]:
start111 = datetime.datetime.now()
for i in np.unique(df['race/ethnicity']):
  print(df[df['race/ethnicity']==i]['reading score'].mean())
end111 = datetime.datetime.now()
print("Время выполнения:", end111-start111)

print("\n")

start101 = datetime.datetime.now()
print(df.groupby(['race/ethnicity'])['reading score'].mean())
end101 = datetime.datetime.now()
print("Время выполнения:", end101-start101)

print("\n")

print("Без использования циклов операция была выполнена в", ( round((end111-start111)/(end101-start101),2) ), "раз быстрее.")

64.67415730337079
67.35263157894737
69.10344827586206
70.03053435114504
73.02857142857142
Время выполнения: 0:00:00.007560


race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64
Время выполнения: 0:00:00.002616


Без использования циклов операция была выполнена в 2.89 раз быстрее.


In [208]:
start112 = datetime.datetime.now()
for i in np.unique(df['education']):
  print(df[df['education']==i]['writing score'].min())
end112 = datetime.datetime.now()
print("Время выполнения:", end112-start112)

print("\n")

start102 = datetime.datetime.now()
print(df.groupby(['education'])['writing score'].min())
end102 = datetime.datetime.now()
print("Время выполнения:", end102-start102)

print("\n")

print("Без использования циклов операция была выполнена в", ( round((end112-start112)/(end102-start102),2) ), "раз быстрее.")

35
38
15
46
19
10
Время выполнения: 0:00:00.006541


education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64
Время выполнения: 0:00:00.002394


Без использования циклов операция была выполнена в 2.73 раз быстрее.


## Задание 12

Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.

Это можно сделать с помощью сводных таблиц – [pivot_table](https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas).

In [209]:
df.pivot_table(index=['gender','education'], values=['math score',	'reading score',	'writing score'], aggfunc='mean')

math score  reading score  writing score
gender education                                                   
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

## Задание 13

Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [210]:
df['Math_PassStatus'] = np.select([df['math score']<50], ['F'], default='P')
df['Reading_PassStatus'] = np.select([df['reading score']<50], ['F'], default='P')
df['Writing_PassStatus'] = np.select([df['writing score']<50], ['F'], default='P')

In [211]:
print('Экзамен по математике:')
print(df['Math_PassStatus'].value_counts())
print('\n')
print('Экзамен по чтению:')
print(df['Reading_PassStatus'].value_counts())
print('\n')
print('Экзамен по письму:')
print(df['Writing_PassStatus'].value_counts())

Экзамен по математике:
P    865
F    135
Name: Math_PassStatus, dtype: int64


Экзамен по чтению:
P    910
F     90
Name: Reading_PassStatus, dtype: int64


Экзамен по письму:
P    886
F    114
Name: Writing_PassStatus, dtype: int64




```
Экзамен по математике, чтению и письму сдали 865, 910 и 886 человек соответственно.
```



## Задание 14

Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [212]:
df['OverAll_PassStatus'] = np.select([(df['Math_PassStatus']=='P') & (df['Reading_PassStatus']=='P') & (df['Writing_PassStatus']=='P')],
          ['P'], default='F')

In [213]:
df['OverAll_PassStatus'].value_counts()

P    812
F    188
Name: OverAll_PassStatus, dtype: int64



```
Все три экзамена успешно сдали 812 человек.
```



## Задание 15

Переведем баллы в оценки

**Система перевода баллов в оценки:**


* $x > 90 = A$
* $80 < x \leq 90 = B$
* $70 < x \leq 80 = C$
* $60 < x \leq 70 = D$
* $50 < x \leq 60 = E$
* $x \leq 50 = F (Fail) $

Пусть $x - $ средний балл студента за три экзамена.  

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

In [215]:
def GetGrade(average_mark):
    if average_mark > 90:
      return "A"
    if (average_mark <= 90) & (average_mark > 80):
      return "B"
    if (average_mark <= 80) & (average_mark > 70):
      return "C"  
    if (average_mark <= 70) & (average_mark > 60):
      return "D"  
    if (average_mark <= 60) & (average_mark > 50):
      return "E" 
    else:
      return "F"               

In [216]:
df['Grade'] = df[['math score','reading score', 'writing score']].mean(axis=1).map(GetGrade)

In [220]:
df.tail()

gender race/ethnicity  ... OverAll_PassStatus Grade
995  female        group E  ...                  P     A
996    male        group C  ...                  P     E
997  female        group C  ...                  P     D
998  female        group D  ...                  P     C
999  female        group D  ...                  P     B

[5 rows x 14 columns]

In [217]:
df['Grade'].value_counts().sort_index()

A     50
B    144
C    253
D    260
E    184
F    109
Name: Grade, dtype: int64